import { Bucket } from 'src/types';

export const SAMPLE_DATA: Bucket[] = [
  {
    id: 1,
    ownerId: 1,
    categories: ['운동', '취미'],
    title: '매일 아침 조깅하기',
    description: '아침 6시에 같이 조깅해요',
    participant: [{ userId: 1, nickname: '러너1', profile: 'profile1.jpg' }],
    maxCapacity: 5,
    progressStatus: 0,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    createdAt: '2023-12-31',
  },
  {
    id: 2,
    ownerId: 2,
    categories: ['여행', '문화'],
    title: '유럽 배낭여행 동행',
    description: '여름 유럽 2주 배낭여행 같이가실 분!',
    participant: [
      { userId: 2, nickname: '여행러버', profile: 'profile2.jpg' },
      { userId: 3, nickname: '세계여행가', profile: 'profile3.jpg' },
    ],
    maxCapacity: 4,
    progressStatus: 0,
    startDate: '2024-07-01',
    endDate: '2024-07-15',
    createdAt: '2024-01-02',
  },
  {
    id: 3,
    ownerId: 3,
    categories: ['학습', '취미'],
    title: '토익 900점 스터디',
    description: '매주 토요일 스터디하면서 같이 성장해요',
    participant: [{ userId: 3, nickname: '영어왕', profile: 'profile4.jpg' }],
    maxCapacity: 6,
    progressStatus: 1,
    startDate: '2024-02-01',
    endDate: '2024-05-31',
    createdAt: '2024-01-03',
  },
  {
    id: 4,
    ownerId: 4,
    categories: ['음식', '문화'],
    title: '월 1회 맛집 탐방',
    description: '서울 숨은 맛집 찾아다니기',
    participant: [
      { userId: 4, nickname: '맛집헌터', profile: 'profile5.jpg' },
      { userId: 5, nickname: '미식가', profile: 'profile6.jpg' },
    ],
    maxCapacity: 4,
    progressStatus: 1,
    startDate: '2024-01-15',
    endDate: '2024-12-15',
    createdAt: '2024-01-04',
  },
  {
    id: 5,
    ownerId: 5,
    categories: ['봉사', '문화'],
    title: '주말 돌봄센터 봉사활동',
    description: '매월 마지막 주 토요일 아이들과 함께하는 시간',
    participant: [
      { userId: 5, nickname: '따뜻한마음', profile: 'profile7.jpg' },
    ],
    maxCapacity: 8,
    progressStatus: 0,
    startDate: '2024-02-24',
    endDate: '2024-12-28',
    createdAt: '2024-01-05',
  },
  {
    id: 6,
    ownerId: 6,
    categories: ['취미', '문화'],
    title: '한달 한권 독서모임',
    description: '매월 마지막 주 일요일 오후 2시 강남 독서모임',
    participant: [
      { userId: 6, nickname: '책벌레', profile: 'profile8.jpg' },
      { userId: 7, nickname: '독서광', profile: 'profile9.jpg' },
      { userId: 8, nickname: '책사랑', profile: 'profile10.jpg' },
    ],
    maxCapacity: 8,
    progressStatus: 1,
    startDate: '2024-01-28',
    endDate: '2024-12-29',
    createdAt: '2024-01-06',
  },
  {
    id: 7,
    ownerId: 7,
    categories: ['운동', '취미'],
    title: '주말 등산 동호회',
    description: '격주 토요일 서울 근교 산 등반',
    participant: [{ userId: 7, nickname: '산사랑', profile: 'profile11.jpg' }],
    maxCapacity: 10,
    progressStatus: 0,
    startDate: '2024-03-01',
    endDate: '2024-11-30',
    createdAt: '2024-01-07',
  },
  {
    id: 8,
    ownerId: 8,
    categories: ['학습', '취미'],
    title: '코딩 스터디',
    description: '주 2회 알고리즘 문제 풀이',
    participant: [
      { userId: 8, nickname: '코딩왕', profile: 'profile12.jpg' },
      { userId: 9, nickname: '개발자', profile: 'profile13.jpg' },
    ],
    maxCapacity: 5,
    progressStatus: 1,
    startDate: '2024-02-01',
    endDate: '2024-06-30',
    createdAt: '2024-01-08',
  },
  {
    id: 9,
    ownerId: 9,
    categories: ['기타', '취미'],
    title: '보드게임 모임',
    description: '매주 금요일 저녁 신촌에서 보드게임!',
    participant: [
      { userId: 9, nickname: '게임마스터', profile: 'profile14.jpg' },
    ],
    maxCapacity: 6,
    progressStatus: 0,
    startDate: '2024-02-02',
    endDate: '2024-12-27',
    createdAt: '2024-01-09',
  },
  {
    id: 10,
    ownerId: 10,
    categories: ['음식', '취미'],
    title: '베이킹 클래스',
    description: '월 2회 홈베이킹 모임',
    participant: [
      { userId: 10, nickname: '베이커리', profile: 'profile15.jpg' },
      { userId: 11, nickname: '제빵왕', profile: 'profile16.jpg' },
    ],
    maxCapacity: 4,
    progressStatus: 2,
    startDate: '2024-01-10',
    endDate: '2024-03-24',
    createdAt: '2024-01-10',
  },
];
